apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: hotel-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ubaidrza/mmv3-auth:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hotel-config
            - secretRef:
                name: hotel-secrets
          volumeMounts:
            - name: firebase-key
              mountPath: /app/firebase-service-account.json
              subPath: firebase-service-account.json
              readOnly: true
      volumes:
        - name: firebase-key
          secret:
            secretName: firebase-secret