server:
  port: 8084

spring:
  application:
    name: booking-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

firebase:
  service-account-key-path: /app/firebase-service-account.json
  project-id: ${FIREBASE_PROJECT_ID}

jwt:
  secret: ${JWT_SECRET}

auth-service:
  url: http://localhost:8080

hotel-service:
  url: http://localhost:8082

room-service:
  url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    com.ubaid.booking_service: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: docker

auth-service:
  url: http://auth-service:8080

hotel-service:
  url: http://hotel-listing-service:8082

room-service:
  url: http://room-listing-service:8083