apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-listing-service
  namespace: hotel-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-listing-service
  template:
    metadata:
      labels:
        app: hotel-listing-service
    spec:
      containers:
        - name: hotel-listing-service
          image: ubaidrza/mmv3-hotel-listing-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: hotel-config
            - secretRef:
                name: hotel-secrets
          volumeMounts:
            - name: firebase-key
              mountPath: /app/firebase-service-account.json
              subPath: firebase-service-account.json
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: firebase-key
          secret:
            secretName: firebase-secret