spring:
  application:
    name: hotel-management
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: 8080

app:
  name: Hotel Management System

firebase:
  service-account-key-path:
  project-id: ${FIREBASE_PROJECT_ID}

jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012}
  access-token-ms: 900000  # 15 minutes
  refresh-token-ms: 604800000  # 7 days
  cleanup:
    cron: "0 0 2 * * *"  # Daily at 2 AM

otp:
  expiry-minutes: 10

logging:
  level:
    com.hotel.management: DEBUG
    org.springframework.security: DEBUG