server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: hotel-listing-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

firebase:
  service-account-key-path: ${FIREBASE_SERVICE_ACCOUNT_KEY_PATH}
  project-id: ${FIREBASE_PROJECT_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET}

auth-service:
  url: ${AUTH_SERVICE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.ubaid.hotel_listing_service: INFO
    com.ubaid.hotel_listing_service.config.SecurityConfig: DEBUG
    com.ubaid.hotel_listing_service.service.JwtService: DEBUG
    com.ubaid.hotel_listing_service.interceptor: DEBUG
    org.springframework.security: INFO
    org.springframework.security.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
